[server]
port=":80"

#####################################################################
# SSL configuration
#
# [server.ssl]
# key=""
# cert=""

# [session]
# secret=""
# expires=""

#####################################################################
# Database configuration, by default using SQLite3.
# You can also use postgres and mysql. See the documentation
# for more details.

[database]
driver="::DB_DRIVER::"
datasource="::DB_DATASOURCE::"

#####################################################################
# Open Registration allows users to self-register for Drone.
# This is recommended if Drone is being hosted behind a
# firewall.
#
# When false, the system admin will need to manually add
# users to Drone through the admin screens.
#
# [registration]
# open=true

[github]
client="::GITHUB_CLIENT::"
secret="::GITHUB_SECRET::"

# [github_enterprise]
# client=""
# secret=""
# api=""
# url=""
# private_mode=false

# [bitbucket]
# client=""
# secret=""

[gitlab]
url="::GITLAB_URL::"

#####################################################################
# SMTP configuration for Drone. This is required if you plan
# to send email notifications for build statuses.
#
# [smtp]
# host=""
# port=""
# from=""
# user=""
# pass=""

[worker]
# cert=""
# key=""
nodes=[
    ::WORKERS_URL::
]
